#!/bin/sh
### BEGIN INIT INFO
# Provides: vncboot
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start VNC server at boot time
### END INIT INFO

export USER='pi'
eval cd ~$USER

export USER HOME

case "$1" in
    start)
        echo "starting VNC server"
        # insert your setting for a VNC session, e.g. port:0
        su $USER -c '/user/bin/vncserver -geometry 1024x768 -depth 24 :0'
        ;;

    stop)
        echo "stopping VNC server"
        su $USER -c '/user/bin/vncserver -kill :0'
        ;;

    *)
        echo "Usage: /etc/init.d/vncboot {start|stop}"
        exit 1
        ;;

esac

exit 0
